services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    #volumes:
    #  - ./data:/app/data  # pour accéder au même fichier DuckDB
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://backend:8000  # L'URL du backend à utiliser dans Streamlit
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://backend:8000  # L'URL du backend à utiliser dans Streamlit 
    

networks:
  app-network:
    driver: bridge
